---

USER_NAME: "{{ lookup('env', 'USER') }}"
HOME_DIR: "/home/{{ USER_NAME }}"
HOST_NAME: "{{ lookup('file', '/etc/hostname') }}"

NODE_VERSION: "20.15.1"
GO_VERSION: "1.23.0"
RAW_THERAPEE_VERSION: "5.10"
OBSIDIAN_VERSION: "1.8.7"
TERRAFORM_VERSION: "1.9.3"

yubico_authenticator_version: "7.0.0"
localsend_version: "1.15.4"

COMMON_PACKAGES:
  - alsa-tools                     # Tools for managing audio output
  - age                            # A simple, modern and secure file encryption tool
  - arch-audit                     # Searching for vulnerable arch-packages
  #- ack                            # ack is a grep-like source code search tool. (I don't use it anymore, but without the ack plugin in nvim won't work)
  - bat                            # A combination of cat and less written in Rust https://github.com/sharkdp/bat
  # - brave-browser                  # Brave browser, alternative for Chromium with builtin sync and ad-block
  - btop                           # A monitor of system resources, bpytop ported to C++
  - otf-comicshanns-nerd           # Another nice patched Nerdfont
  - curl                           # Http-Requests from the commandline
  - chromium                       # Browser for working stuf
  - duf                            # Disk Usage/Free Utility
  - dunst                          # Simple notifications daemon https://wiki.archlinux.org/title/Dunst#Installation
  - easytag                        # Managing id3 tags of MP3 files
  - evince                         # Another Pdf-Viewer
  - eza                            # A nice replacement for the ls command
  - fastfetch                      # Like Neofetch, just faster
  - filezilla                      # Transferring data with SSH
  - firefox                        # My current browser with synchronization feature
  - fzf                            # Fuzzyfinder for the commandline
  - fx                             # Better navigation for large JSON on the commandline
  - gopass                         # Passwordmanagement in the commandline (Better than pass)
  - gedit                          # The Gnome editor
  - ghostty                        # Fast, native, feature-rich terminal emulator pushing modern features
  - gvfs-dnssd                     # Virtual filesystem implementation for GIO - DNS-SD and WebDAV backend (Required by Nautilus for accessing Mailbox WebDav)
  - gthumb                         # Image browser and viewer for the GNOME Desktop
  # - gvfs-mtp                       # Drivers for support mounting Android devices
  - htop                           # Better tool to show system resource usage in the commandline
  - inxi                           # Show hardware information about my computer
  - keepassxc                      # Manage my passwords with a GUI
  - keychain                       # reuse ssh-agent and/or gpg-agent between logins
  - luarocks                       # Required by Mason in Neovim
  - lf                             # A terminal file manager inspired by ranger
  - mplayer                        # Videoplayer for the terminal
  - nautilus                       # The file explorer from Gnome
  - neovim                         # the better version of VIM which is the better version of VI
  - network-manager-applet         # Managing network connection from the i3 toolbar
  - nsxiv                          # Imageviewing in the terminal
  - ncdu                           # Show disk usage
  - ttf-fira-code                  # My favorite fonts for source code with ligatures
  - ttf-nerd-fonts-symbols-common
  - pavucontrol                    # Pulseaudio Audio Control
  - pdfpc                          # PdfViewer for presentations
  - pinta                          # Image-Editor
  - ripgrep                        # The better grep alternative, written in Rust
  - scrot                          # Screenshot-Tool
  - seahorse                       # Key management SSH and GPG
  - simple-scan                    # Scanning of documents and photos
  - sshpass                        # Pass passwords to the ssh tool
  - television                     # A general purpose fuzzy finder for your terminal
  - tgpt                           # AI on the commandline
  - tree                           # Commandline tool to show directory tree
  - veracrypt                      # Using encrypted file containers
  - screenkey                      # Show the current typed key on the screen (helpful for presentations)
  - watchexec                      # Required for running commands when a file will changed
  - xsel                           # Commandlinetool for the clipboard
  - zathura                        # A Pdf viewer for the terminal
  - zathura-pdf-mupdf              # Plugin for Zahthura to show Pdf and Epubs
  - zoxide                         # A smarter cd command for your termina

AUR_PACKAGES:
  - moc-pulse # MusicPlayer for the terminal

IS_NOTEBOOK: false

CONFIG_FILES_CHROMIUM_ZOOM: 1.0
CONFIG_FILES_BRAVE_ZOOM: 1.1
DOTFILES_SCREEN_DPI: 144
DOTFILES_GDK_DPI_SCALE: 1

JABASOFT_DS_IP_ADDRESS: '192.168.178.21'
JABASOFT_DS_SSH_PORT: 26

MAILBOX_DRIVE_USER: 'jan.baer'

GLOBAL_NPM_PACKAGES:
  - eslint
  - typescript
  - ts-node               # Required to execute TS file directly from command line
  - prettier
  - google-translate-cli  # Google Translate from the command line
  - live-server           # Running a webserver from the current directory
  - npkill                # Tool for cleanup node_modules folders from current working tree
  - npm-check             # Checks current project for outdated or unused npm modules
  - neovim                # Neovim client API and neovim remote plugin provider
  - tree-sitter           # Required for Neovim
  - tree-sitter-cli       # Required for Neovim

ATUIN_USER_NAME: "janbaer"
ATUIN_PASSWORD: "{{ vault_atuin_password }}"
ATUIN_KEY: "{{ vault_atuin_key }}"

HYPRLAND_MONITOR_CONF: ",preferred,auto,auto"
