---

- name: Check if cargo is installed
  stat:
    path: /usr/bin/cargo
  register: cargo_stats
  ignore_errors: yes
  changed_when: false
  check_mode: false

- name: Download Installer
  when: cargo_stats.stat.exists == false
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: yes

- name: Install rust/cargo
  when: cargo_stats.stat.exists == false
  shell: /tmp/sh.rustup.rs -y

- name: Check if rustc was installed successfully.
  shell: "/home/{{USER_NAME}}/.cargo/bin/rustc --version"
  register: rustc_check
  changed_when: false
  failed_when: rustc_check.failed

- debug:
    msg: "Rustc installed version: {{ rustc_check.stdout }}"

- name: Install rust-analyzer
  become: true
  pacman:
    name:
      - rust-analyzer
    state: present
    force: false
