# vim:ft=yaml.ansible
---

- include_tasks: ./yubico.yml

- name: Download and install yubico-authenticator
  include_tasks: ./authenticator.yml
  tags:
    - yubico
    - yubico-authenticator

- name: Add pamd configuration to be able to login with Yubikey
  include_tasks: ./pamd-config.yml
  tags:
    - yubico
    - yubico-pamd
