---

# See also https://linuxhint.com/install_configure_kvm_archlinux/

- name: Remove conflicting packages before installing required packages
  become: true
  community.general.pacman:
    name:
      - iptables
    state: absent

- name: Install required packages for using KVM
  become: true
  community.general.pacman:
    name:
      - qemu-full
      - virt-manager
      - virt-viewer
      - dnsmasq
      - vde2
      - bridge-utils
      - openbsd-netcat
      - ebtables
      - libguestfs
    state: present

- name: Install additional packages from AUR
  aur:
    use: yay
    name:
      - libguestfs

- name: Libvirtd systemd service
  become: true
  service:
    name: libvirtd
    enabled: true
    state: started

- name: add user to libvirt group
  become: true
  user:
    name: '{{ USER_NAME }}'
    groups: [libvirt]
    append: true
  notify:
    - Restart libvirtd service
