# vim:ft=yaml.ansible
---

- name: Update pacman cache
  become: true
  pacman:
    update_cache: yes

- name: Update pacman package lists
  become: true
  command: /usr/bin/pacman -Syy --noconfirm

- name: Install all required packages
  become: true
  pacman:
    name:
      - hyprland                        # Hyprland is a highly customizable dynamic tiling Wayland compositor
      - hyprpaper                       # Show wallpapers in Hyprland
      - hypridle
      - hyprlock
      - waybar                          # Highly customizable Wayland bar for Sway and Wlroots based compositors.
      - rofi                            # A window switcher, application launcher and dmenu replacement
      - dunst                           # Show user messages
      - feh                             # Selecting Images for the wallpaper
      - xdg-desktop-portal-hyprland     # xdg-desktop-portal backend for hyprland
      - xdg-desktop-portal
      - ttf-font-awesome                # Required for showing signs in Waybar
      - wl-clipboard                    # Handling system-wide clipboard in Wayland
      - qt5-wayland                     # Provides APIs for Wayland
      - qt6-wayland                     # Provides APIs for Wayland
      - cliphist                        # The new clipboard manager
      - grim                            # Required for making screenshots
      - slurp                           # Required for making screenshots
      - swappy                          # Required for making screenshots
      - yad                             # Show a GTK popup from the commandline
      - blueman                         # Toolbar applet for Bluetooth
      - pasystray
      - volumeicon
      - brightnessctl                   # Control monitor brightness with fn-keys
    state: present
    force: false

- name: Install packages for building aur-package
  become: true
  pacman:
    name:
      - pkgconfig
      - cmake
    state: present
    force: false

- name: Install packages from aur
  aur:
    use: yay
    name:
      - wlogout                         # Show a nice exit screen with multiple options
      - nwg-drawer-bin                  # A drawer for wayland compositors
      - nwg-look-bin                    # A configuration tool for GTK settings in Wayland
      - wdisplays                       # Configuring display in Wayland
  ignore_errors: true

- name: Configure monitor.conf with template
  ansible.builtin.template:
    src: monitor.conf.j2
    dest: ~/.config/hypr/monitor.conf
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: "0600"

- name: Copy pamd config for hyprlock
  ansible.builtin.copy:
    src: pamd-hyprlock
    dest: /etc/pam.d/hyprlock
    owner: root
    group: root
    mode: 0644

