---

- name: Copy Huawei soundfix files
  ansible.builtin.copy:
    src: huawei-soundfix.sh
    dest: /usr/bin/
    owner: root
    group: root
    mode: 0755
  become: yes
  when: ansible_product_name == 'HUAWEI MateBook X' and ansible_product_version == '2.0'

- name: Copy Huawei service definition file
  ansible.builtin.copy:
    src: huawei-soundfix.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_product_name == 'HUAWEI MateBook X' and ansible_product_version == '2.0'

- name: Enable and start Huawei soundfix service
  ansible.builtin.service:
    name: huawei-soundfix
    enabled: true
    daemon_reload: true
  become: yes
  when: ansible_product_name == 'HUAWEI MateBook X' and ansible_product_version == '2.0'
