---
- name: Run all playbooks
  hosts: localhost

- import_playbook: playbooks/pacman.yml
- import_playbook: playbooks/develop.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/zsh.yml
- import_playbook: playbooks/i3.yml
- import_playbook: playbooks/tmux.yml
- import_playbook: playbooks/dotfiles.yml
- import_playbook: playbooks/nodejs.yml
- import_playbook: playbooks/vim.yml

  # vars_prompt:
    # - name: "user_password"
      # prompt: "Enter password"
      # private: yes
