---

- hosts: all
  roles:
    - { role: base-system, tags: [base] }
    - { role: config-files, tags: [config-files] }
    - { role: cron-jobs, tags: [cron, cron-jobs] }
    - { role: develop, tags: [develop] }
    - { role: golang, tags: [golang, go] }
    - { role: nodejs, tags: [nodejs] }
    - { role: rust, tags: [rust] }
    - { role: k8s, tags: [k8s] }
    - { role: python, tags: [python, never] }
    - { role: docker, tags: [docker] }
    - { role: i3, tags: [i3, never] }
    - { role: tmux, tags: [tmux] }
    - { role: zsh, tags: [zsh] }
    - { role: hyprland, tags: [hyprland, never] }
    - { role: ssh-key, tags: [ssh, ssh-key] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: vscode, tags: [vscode] }
    - { role: vagrant, tags: [vagrant, never] }
    - { role: mailbox-drive, tags: [mailbox, mailbox-drive, never] }
    - { role: security, tags: [security] }
    - { role: pipewire, tags: [pipewire, never] }
    - { role: yubico, tags: [yubico, never] }

- hosts: private_pcs
  roles:
    - { role: gpg, tags: [gpg, pass] }
    - { role: nas-mounts, tags: [nas-mounts] }
    - { role: borg, tags: [borg] }

- hosts: desktop_pcs
  roles:
    - { role: kvm, tags: [kvm] }

- hosts: notebooks
  roles:
    - { role: libinput-gestures, tags: [never, libinput, touchpad] }
    - { role: huawei-soundfix, tags: [never, huawei] }
