---

- name: Install vagrant and additional tools
  become: true
  pacman:
    name:
      - vagrant
    state: present

- name: Install libvirt plugin
  command:
    cmd: "vagrant plugin install vagrant-libvirt"
