# vim:ft=yaml.ansible
---

- name: Install vagrant and additional tools
  become: true
  pacman:
    name:
      - vagrant
    state: present

- name: Install libvirt plugin
  ansible.builtin.command:
    cmd: "vagrant plugin install vagrant-libvirt"
  environment:
    VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT: 1
