# vim:ft=yaml.ansible
---

- name: Install VisualStudioCode from aur
  aur:
    use: yay
    name: visual-studio-code-bin

- name: Install vscode extensions
  command: code --install-extension {{item}}
  with_items:
    - dracula-theme.theme-dracula
    - alex-pattison.theme-cobalt3
    - golang.Go
    - Orta.vscode-jest
    - ryanluker.vscode-coverage-gutters
    - hbenl.vscode-test-explorer
    - eamodio.gitlens
    - christian-kohler.path-intellisense
    - emmanuelbeziat.vscode-great-icons
    - svelte.svelte-vscode
    - pinage404.rust-extension-pack
    - swellaby.vscode-rust-test-adapter
    - redhat.vscode-yaml
    - redhat.ansible
    # - ms-azuretools.vscode-docker
    # - ms-vscode-remote.remote-ssh
  ignore_errors: true
