---

  - name: install packages from aur
    become_user: "{{ USER_NAME }}"
    aur:
      use: trizen
      name:
        - libinput-gestures

  - name: add user to input group
    user:
      name: '{{ USER_NAME }}'
      groups: input
      append: yes


