---

- name: Check if volta exists
  ansible.builtin.stat:
    path: "{{ VOLTA_HOME  }}/bin/volta"
  register: VOLTA_CHECK

- name: Install volta
  ansible.builtin.shell:
    cmd: "curl https://get.volta.sh | bash"
    creates: "{{ VOLTA_HOME }}/bin/volta"
  when: not VOLTA_CHECK.stat.exists

- name: Install Node.js version {{ NODE_VERSION }}
  ansible.builtin.command: "volta install node@{{ NODE_VERSION }}"
  environment:
    VOLTA_HOME: "{{ VOLTA_HOME }}"
    PATH: "$PATH:{{ VOLTA_HOME }}/bin"

- name: Install yarn
  ansible.builtin.command: "volta install yarn@1"
  environment:
    VOLTA_HOME: "{{ VOLTA_HOME }}"
    PATH: "$PATH:{{ VOLTA_HOME }}/bin"

- name: Install required global npm modules
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: present
  environment:
    VOLTA_HOME: "{{ VOLTA_HOME }}"
    PATH: "$PATH:{{ VOLTA_HOME }}/bin"
  with_items: "{{ GLOBAL_NPM_PACKAGES }}"
  ignore_errors: true

- debug:
    msg: "You need to install tree-sitter and tree-sitter-cli manually, because it fails from here at the moment!!!"
