# vim:ft=yaml.ansible
---

- name: Install Python development tools
  become: true
  pacman:
    name:
      - python-pip
    state: present

- name: Install Python packages
  become: true
  pip:
    name:
      - python-language-server
    state: present
