---

- name: Ensure logfile exists with the correct access rights
  become: true
  copy:
    content: ""
    dest: "/var/log/rsync-{{ HOST_NAME }}.log"
    force: false
    group: sys
    owner: root
    mode: 0666

- name: Backup my home dir every day
  cron:
    name: "rsync-{{ HOST_NAME }}"
    minute: "0"
    job: "JABASOFT_DS_SSH_PORT={{ JABASOFT_DS_SSH_PORT }} /home/jan/bin/rsync-{{ HOST_NAME }}.sh > /var/log/rsync-{{ HOST_NAME }}.log"
  tags: cron
