---

- name: Install timers
  tags: [cron, timers]
  when: timers is defined
  become: true
  block:
    - name: Uploading service file
      template:
          src: timer.service.j2
          dest: "{{ systemd_base_path | default('/etc/systemd/system') }}/{{ item.name }}.service"
          owner: "{{ item.user | default('root') }}"
          group: "{{ item.user | default('root') }}"
          mode: 0644
      with_items: "{{ timers }}"
      notify: Reload systemd

    - name: Uploading timer file
      template:
          src: timer.timer.j2
          dest: "{{ systemd_base_path | default('/etc/systemd/system') }}/{{ item.name }}.timer"
          owner: "{{ item.user | default('root') }}"
          group: "{{ item.user | default('root') }}"
          mode: 0644
      with_items: "{{ timers }}"
      notify: Reload systemd

    - name: Enabling timers
      systemd:
          name: "{{ item.name }}.timer"
          state: restarted
          enabled: true
          masked: false
          daemon_reload: true
          scope: "{{ systemd_scope | default('system') }}"
      with_items: "{{ timers }}"
