# vim:ft=yaml.ansible
---

- name: Create XXX dirs
  become: true
  file:
    path: "/media/{{ item }}"
    state: directory
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
  with_items:
    - "XXX"
    - "XXX1"
    - "XXX2"
    - "XXX3"
    - "XXX4"
    - "XXX5"
    - "XXX-KG"
    - "MyDocuments"
    - "MyNotes"

- name: Create mount dirs
  become: true
  file:
    path: "/media/{{ USER_NAME }}/{{ item }}"
    state: directory
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
  with_items:
    - "daten"
    - "home"
    - "music"
    - "photo"
    - "setup"
    - "video"
    - "pve/music"

- name: Enable nfs-client.target service
  service:
    name: nfs-client.target
    state: started
    enabled: yes

- name: Add mounts for network-shares
  become: true
  lineinfile:
    dest: /etc/fstab
    line: "{{ item }}"
  with_items:
    - "//jabasoft-ds/homes/jan	/media/jan/home cifs credentials=/home/jan/.smb,vers=2.0,user,rw,noauto 0 0"
    - "//jabasoft-ds/photo 	/media/jan/photo cifs credentials=/home/jan/.smb,vers=2.0,user,rw,noauto 0 0"
    - "//jabasoft-ds/music 	/media/jan/music cifs credentials=/home/jan/.smb,vers=2.0,user,rw,noauto 0 0"
    - "//jabasoft-ds/video 	/media/jan/video cifs credentials=/home/jan/.smb,vers=2.0,user,rw,noauto 0 0"
    - "//jabasoft-ds/daten 	/media/jan/daten cifs credentials=/home/jan/.smb,vers=2.0,user,rw,noauto 0 0"
    - "//jabasoft-ds/setup 	/media/jan/setup cifs credentials=/home/jan/.smb,vers=2.0,user,rw,noauto 0 0"
    - "jabasoft-pve:/data/metube/mp3 /media/jan/pve/music nfs nfsvers=4,rw,auto 0 0"
