---
- name: Install basic development tools
  become: true
  pacman:
    name:
      - "base-devel"
      - "cmake"
      - "ctags"         # Its required for the tags plugin in VIM
      - "gitg"          # GUI for Git
      - "highlight"     # Higlighting sourcecode
      - "jq"            # Tool for querying json in the commandline
      - "httpie"        # My favorite tools for HTTP request in the commandline
      - "meld"          # Difftool with UI
    state: present

- name: Install developer packages from aur
  aur:
    use: yay
    name:
      - git-extras
      - http-prompt
