# vm:ft=yaml.ansible
---

- name: Install basic development tools
  become: true
  pacman:
    name:
      - base-devel
      - codespell             # Finding typos in my code not only in comments from commandline or in Nvim with null_ls
      - ctags                 # Its required for the tags plugin in VIM
      - dnsutils              # nslookup and dig
      - fd                    # Required by Neovim Telescope plugin to browse all projects
      - gitui                 # Another nice terminal UI written for Git written in Rust
      - gojq                  # Rewrite of JQ but with Go without any dependencies
      - highlight             # Highlighting sourcecode
      - httpie                # My favorite tools for HTTP request in the commandline
      - jc                    # Converts the output of popular command-line tools and file-types to JSON
      # - jq                    # Tool for querying json in the commandline
      - jless                 # a command-line JSON viewer https://jless.io/
      - lumen                 # Instant AI Git Commit message, Git changes summary from the CLI
      - make
      - meld                  # Difftool with UI
      - yamllint              # Linting my yaml files from the commandline or in Neovim
      - ansible-lint          # Same for Ansible files
      - dog                   # A dns-lookup tool (like dig) https://dns.lookup.dog/
      - pwgen                 # Password generator from the commandline. Use`pwgen 30 -1` to generate one password with a length of 30 characters
      - molecule              # Testing Ansible roles
      - tig                   # My favorite tool for Git in the terminal
      - tokei                 # Count your code, quickly - https://github.com/XAMPPRocky/tokei
    state: present

- name: Install developer packages from aur
  aur:
    use: yay
    name:
      - aur/git-extras
      - python-xyzservices
  ignore_errors: true

- include_tasks: ./terraform.yml
  tags: terraform

- include_tasks: ./molecule.yml
  tags: molecule, never

- include_tasks: ./atuin.yml
  tags: atuin

- include_tasks: ./lazygit.yml
  tags: lazygit
