# vim:ft=yaml.ansible
---

- name: Create .ssh dir if not exists
  file:
    path: "{{ HOME_DIR }}/.ssh"
    state: directory

- name: Copy encrypted files to .ssh
  copy:
    src: "{{ item }}"
    dest: "{{ HOME_DIR }}/.ssh/{{ item }}"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: 0600
  with_items:
    - id_rsa
    - id_ed25519
    - ssh_hetzner_storagebox
    - known_hosts

- name: Copy pub keys to .ssh
  copy:
    src: "{{ item }}"
    dest: "{{ HOME_DIR }}/.ssh/{{ item }}"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: 0644
  with_items:
    - id_rsa.pub
    - id_ed25519.pub
    - ssh_hetzner_storagebox.pub
