---

- name: Install required packages for Borg backup
  become: true
  community.general.pacman:
    name:
      - python-llfuse
      - borg
    state: present
    force: false

- name: Install autocompletion for Borg backup
  become: true
  get_url:
    url: https://gist.githubusercontent.com/mrkmg/dbabe71b379adb282ca6ef4568d40f5a/raw/fd039e54e51ee7b931e4c34a2cb8e1ee5dfb0882/borg-completion.zsh
    dest: /usr/share/zsh/site-functions/_borg
    mode: 644

- name: Make sure that directory for mounting borg repo exists
  file:
    path: /mnt/borg
    state: directory
    mode: 0700

