---

- name: Download Obsidian {{ OBSIDIAN_VERSION }} AppImage
  become: true
  get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ OBSIDIAN_VERSION }}/Obsidian-{{ OBSIDIAN_VERSION }}.AppImage"
    dest: "/usr/bin/obsidian"
    mode: 0755
