---

timers:
  - name: backup-to-usb
    user: "jan"
    command: "{{ HOME_DIR }}/bin/rsync-to-usb.sh"
    on_calendar: "hourly"
    persistent: true
    accuracy_sec: "15sec"
    randomized_delay_sec: "15m"
  - name: backup-mailbox-drive-to-usb
    user: "jan"
    command: "{{ HOME_DIR }}/bin/rsync-mailbox-drive-to-usb.sh"
    on_calendar: "hourly"
    persistent: true
    accuracy_sec: "15sec"
    randomized_delay_sec: "15m"
  - name: backup-to-nas
    user: "jan"
    command: "{{ HOME_DIR }}/bin/rsync-to-nas.sh"
    on_calendar: "hourly"
    environment: "JABASOFT_DS_SSH_PORT={{ JABASOFT_DS_SSH_PORT }}"
    persistent: true
    accuracy_sec: "15sec"
    randomized_delay_sec: "15m"
  - name: backup-mailbox-drive-to-nas
    user: "jan"
    command: "{{ HOME_DIR }}/bin/rsync-mailbox-drive-to-nas.sh"
    on_calendar: "hourly"
    environment: "JABASOFT_DS_SSH_PORT={{ JABASOFT_DS_SSH_PORT }}"
    persistent: true
    accuracy_sec: "15sec"
    randomized_delay_sec: "15m"

