---

- name: Copy Gpg files to Home folder
  copy:
    src: "gpg-agent.conf"
    dest: "{{ HOME_DIR }}/.gnupg/gpg-agent.conf"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
    mode: 0600

- name: Copy Gpg files to Home folder
  copy:
    src: "{{ item }}"
    dest: "{{ HOME_DIR }}/{{ item }}"
    owner: "{{ USER_NAME }}"
    group: "{{ USER_NAME }}"
  with_items:
    - jan.asc

- name: Check if my gpg key was imported before
  shell: "gpg --list-keys"
  register: GPG_KEYS
  ignore_errors: true

- name: Import my gpg key
  shell: "gpg --batch --passphrase={{ GPG_PASSWORD }} --import {{ HOME_DIR }}/jan.asc "
  when: "GPG_KEYS.stdout is not search(USER_NAME)"

- name: Delete Gpg files after import
  file:
    name: "{{ HOME_DIR }}/{{ item }}"
    state: absent
  with_items:
    - jan.asc

- name: Add ip-address of JABASOFT-DS to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "{{ JABASOFT_DS_IP_ADDRESS}} JABASOFT-DS"
    state: present

- name: Clone my passwords Git repo
  git:
    repo: ssh://jan@jabasoft-ds/volume1/homes/jan/git/pass
    dest: ~/.password-store
