---
- name: install development tools
  hosts: localhost
  become: True

  tasks:
    - name: install development tools
      pacman:
        name:
          - base-devel
          - cmake
          - ctags                   # Its required for the tags plugin in VIM
          - gitg                    # GUI for Git
          - highlight               # Higlighting sourcecode
          - jq                      # Tool for querying json in the commandline
          - httpie                  # My favorite tools for HTTP request in the commandline
          - meld                    # Difftool with UI
        state: present
      become_user: "root"

    - name: Download Go archive
      get_url:
        url: "https://dl.google.com/go/{{ GO_ARCHIVE_NAME }}"
        dest: "/tmp/{{ GO_ARCHIVE_NAME }}"
        mode: 0440
      become_user: "{{ USER_NAME }}"

    - name: Install golang
      unarchive:
        src: "/tmp/{{ GO_ARCHIVE_NAME }}"
        dest: "/usr/local"
      become_user: "root"

    - name: install tools with Go
      become_user: "{{ USER_NAME }}"
      command: go get -u {{ item }}
      become_user: "{{ USER_NAME }}"
      with_items: []

    - name: install developer packages from aur
      become_user: "{{ USER_NAME }}"
      aur:
        use: trizen
        name:
          - git-extras
      become_user: "{{ USER_NAME }}"

