- name: install My dotfile
  hosts: localhost
  become_user: "{{ USER_NAME }}"
  become: true

  tasks:
    - name: Create projects directory
      file:
        path: "{{ HOME_DIR }}/Projects"
        state: directory

    - name: Clone dotfiles
      git:
        repo: https://github.com/janbaer/dotfiles.git
        dest: "{{ HOME_DIR }}/Projects/dotfiles"

    - name: Sync dotfiles
      command: "./sync.sh"
      args:
        chdir: "{{ HOME_DIR }}/Projects/dotfiles"
