- name: install My dotfile
  hosts: localhost
  become_user: "{{ USER_NAME }}"
  become: true

  tasks:
    - name: Create projects directory
      file:
        path: /home/{{ USER_NAME }}/Projects
        state: directory

    - name: Clone dotfiles
      git:
        repo: git@github.com:janbaer/dotfiles.git
        dest: /home/{{ USER_NAME }}/Projects/dotfiles

    - name: Sync dotfiles
      command: "./sync.sh"
      args:
        chdir: /home/{{ USER_NAME }}/Projects/dotfiles
