---
- name: Update pacman packages
  hosts: localhost
  become: True

  tasks:
    - name: update pacman cache
      pacman: update_cache=yes

    - name: install pacman tools
      pacman:
        name: pacman-contrib

    - name: update pacman package lists
      command: /usr/bin/pacman -Syy --noconfirm

    - name: perform full upgrade
      command: /usr/bin/pacman -Su --noconfirm

    - name: Install all util packages
      pacman:
        name:
          - alsa-tools
          - arch-audit
          - curl
          - htop
          - httpie
          - jq
          - fzf
          - inxi
          - ack
          - the_silver_searcher
          - keychain
            keepassx2
          - gopass
          - gedit
          - xclip
          - xsel
          - mplayer
          - moc
          - ranger
          - shotwell
          - pinta
          - scrot
          - tig
          - tree
          - trizen
          - pygmentize
          - flameshot
          - veracrypt
          - network-manager-applet
          - sxiv
          - meld
          - zathura
          - zathura-pdf-mupdf
          - evince
          - pdfpc
          - sshpass
          - ncdu
          - gopass
        state: present
        force: yes

    - name: install packages from aur
      become_user: "{{ USER_NAME }}"
      aur:
        use: trizen
        name:
          - gnome-terminal-transparency

    - name: Install libinput-gesture and configure it
      include_tasks: ./tasks/libinut-gestures.yml
      when: {{ IS_NOTEBOOK == true }}

