---
- name: Update pacman packages
  hosts: localhost
  become: True

  tasks:
    - name: update pacman cache
      pacman: update_cache=yes

    - name: install pacman tools
      pacman:
        name: pacman-contrib

    - name: update pacman package lists
      command: /usr/bin/pacman -Syy --noconfirm

    - name: perform full upgrade
      command: /usr/bin/pacman -Su --noconfirm

    - name: Install all util packages
      pacman:
        name:
          - ack                           # Searching from the commandline (In case that ag will not found anything)
          - alsa-tools                    # Tools for managing audio output
          - arandr                        # GUI for selecting multiple monitors location and resolution
          - arch-audit                    # Searching for vulnerable arch-packages
          - curl                          # Http-Requests from the commandline
          - easytag                       # Managing id3 tags of MP3 files
          - evince                        # Another Pdf-Viewer
          - fzf                           # Fuzzyfinder for the commandline
          - flameshot                     # A better tool for making screenshots
          - gopass                        # Passwordmanagement in the commandline (Better than pass)
          - gedit                         # The Gnome editor
          - gvim                          # Vi IMproved, a programmer's text editor
          - htop                          # Better tool to show system resource usage in the commandline
          - inxi                          # Show hardware informations about my computer
          - keepassxc                     # Manage my passwords with a GUI
          - keychain                      # re-use ssh-agent and/or gpg-agent between logins
          - kitty                         # Terminal with tranparency and glyph fonts
          - mplayer                       # Videoplayer for the terminal
          - moc                           # MusicPlayer for the terminal
          - neofetch                      # Creating a nice splashscreen when starting a new shell
          - network-manager-applet        # Managing network connection from the i3 toolbar
          - ncdu                          # Show disk usage
          - otf-fira-code                 # My favorite fonts for source code with ligatures
          - ttf-fira-code                 # My favorite fonts for source code with ligatures
          - pavucontrol                   # Pulseaudio Audio Control 
          - pdfpc                         # PdfViewer for presentations
          - pinta                         # Image-Editor
          - pygmentize                    # highlights the input file
          - ranger                        # My favorite file manager for the terminal
          - scrot                         # Screenshot-Tool
          - shotwell                      # ImageLibraries with GUI
          - sshpass                       # Pass passwords to the ssh tool
          - the_silver_searcher           # AG is the faster alternative to Ack
          - tig                           # My favorite tool for Git in the terminal
          - tree                          # Commandline tool to show directory tree
          - trizen                        # This is the tool for install additional packages from AUR
          - veracrypt                     # Using encrypted file containers
          - sxiv                          # Imageviewing in the terminal
          - xclip                         # Clipboard usage in the terminal
          - xsel                          # Commandlinetool for the clipboard
          - zathura                       # A Pdf viewer for the terminal
          - zathura-pdf-mupdf             # Plugin for Zahthura to show Pdf and Epubs
        state: present
        force: no

    - name: Install packages from aur
      become: true
      become_user: "{{ USER_NAME }}"
      aur:
        use: trizen
        name:
          - pulseaudio-bluetooth-a2dp-gdm-fix

    - name: Install Youtube-dl from the original location to prevent outdated version
      get_url:
        url: "https://yt-dl.org/downloads/latest/youtube-dl"
        dest: "/usr/local/bin/youtube-dl"
        mode: 0755
      become_user: "root"

    - name: Install libinput-gesture and configure it
      include_tasks: ./tasks/libinut-gestures.yml
      when: IS_NOTEBOOK == true

