---
- name: install everything is needed for Python development
  hosts: localhost
  become: True

  tasks:
    - name: install python development tools
      pacman:
        name:
          - python-pip
        state: present
      become: yes

    - name: install python packages
      pip:
        name:
          - python-language-server
        state: present
      become: yes
