---
- name: Install and configure tmux
  hosts: localhost
  become_user: "{{ USER_NAME }}"
  become: True

  tasks:
    - name: install tmux
      pacman:
        name:
          - tmux
      become_user: root

    - name: Create tmux config dir
      file:
        path: /home/{{ USER_NAME }}/.tmux
        state: directory

    - name: Download plugin tpm
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: /home/{{ USER_NAME }}/.tmux/plugins/tpm
        archive: /tmp/tpm.zip

    - name: Download plugin tmux-resurrect
      git:
        repo: https://github.com/tmux-plugins/tmux-resurrect
        dest: /home/{{ USER_NAME }}/.tmux/plugins/tmux-resurrect
        archive: /tmp/tmux-resurrect.zip

