---
- name: Install and configure tmux
  hosts: localhost
  become: True

  tasks:
    - name: install tmux
      become_user: root
      pacman:
        name:
          - tmux

    - name: Create tmux config dir
      become_user: "{{ USER_NAME }}"
      file:
        path: "{{ HOME_DIR }}/.tmux"
        state: directory

    - name: Download plugin tpm
      become_user: "{{ USER_NAME }}"
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ HOME_DIR }}/.tmux/plugins/tpm"
        archive: /tmp/tpm.zip

    - name: Download plugin tmux-resurrect
      become_user: "{{ USER_NAME }}"
      git:
        repo: https://github.com/tmux-plugins/tmux-resurrect
        dest: "{{ HOME_DIR }}/.tmux/plugins/tmux-resurrect"
        archive: /tmp/tmux-resurrect.zip

