---
- name: Setup my Vim with plugins
  hosts: localhost
  become_user: "{{ username }}"
  become: true

  tasks:
    - name: install vim
      pacman:
        name: gvim
      become_user: root

    - name: Create directory for bundle
      file:
        path: "/home/{{ username }}/.vim/bundle"
        state: directory

    - name: Download vim plugin manager Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim

    - name: Download papercolor theme to suppress error while installing plugins
      git:
        repo: https://github.com/NLKNguyen/papercolor-theme.git
        dest: ~/.vim/bundle/papercolor-theme

    - name: Install and update Vim plugins
      command: "/usr/bin/vim +PluginInstall +qall"

    - name: Build YouCompleteMe
      command: "./install.py --go-completer --ts-completer"
      args:
        chdir: "/home/{{ username }}/.vim/bundle/YouCompleteMe"

    - name: Install and update Go binaries
      command: "/usr/bin/vim +GoInstallBinaries +qall"
