---
- name: Setup my Vim with plugins
  hosts: localhost
  become_user: "{{ USER_NAME }}"
  become: true

  tasks:
    - name: Create required directories
      file:
        path: "/home/{{ USER_NAME }}/.vim/{{item}}"
        state: directory
      become_user: "{{ USER_NAME }}"
      with_items:
        - undo
        - spell
        - autoload
        - plugged

    - name: Download vim plugin manager Plug
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "/home/{{ USER_NAME }}/.vim/autoload/plug.vim"
      become_user: "{{ USER_NAME }}"

    - name: Download papercolor theme to suppress error while installing plugins
      git:
        repo: https://github.com/NLKNguyen/papercolor-theme.git
        dest: ~/.vim/plugged/papercolor-theme
      become_user: "{{ USER_NAME }}"

    - name: Download files for German spell checking
      get_url:
        url: "http://ftp.vim.org/vim/runtime/spell/{{item}}"
        dest: "/home/{{ USER_NAME }}/.vim/spell"
      with_items:
        - de.utf-8.spl
        - de.utf-8.sug

    - name: Install and update Vim plugins
      command: "vim -e -s -S '{{ HOME_DIR }}/.vimrc' -c PlugInstall -c qa"
      register: verification
      changed_when: verification.rc == 1
      failed_when: verification.rc not in [0,1]
      become_user: "{{ USER_NAME }}"

    - name: Install and update Go binaries
      command: "vim -e -s -S '{{ HOME_DIR }}/.vimrc' -c GoInstallBinaries -c qa"
      register: verification
      changed_when: verification.rc == 1
      failed_when: verification.rc not in [0,1]
      become_user: "{{ USER_NAME }}"
