---
- name: Setup zsh
  hosts: localhost
  become_user: "{{ USER_NAME }}"
  become: true

  tasks:
    - name: clone oh-my-zsh
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        update: no

    - name: clone zsh-autosuggestions
      git:
        repo: git://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.zsh/zsh-autosuggestions
        update: no

    - name: set zsh as default shell
      command: "chsh -s /usr/bin/zsh {{ USER_NAME }}"
      become_user: root
