# vim.ft: yaml.ansible
---

- set_fact:
    yubico_authenticator_url: "https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz"
    yubico_authenticator_download_path: "~/Downloads/yubico-authenticator.tar.gz"
    yubico_authenticator_target_path: "/usr/local/bin/yubico-authenticator"

- name: Check if yubico-authenticator is installed
  ansible.builtin.stat:
    path: "{{ yubico_authenticator_target_path }}"
  register: _yubico_authenticator_stat_result

- name: Download and install yubico-authenticator
  when: not _yubico_authenticator_stat_result.stat.exists
  block:
    - name: Download the yubico-authenticator
      ansible.builtin.get_url:
        url: "{{ yubico_authenticator_url }}"
        dest: "{{ yubico_authenticator_download_path }}"
        mode: 0644

    - name: Extract the package
      ansible.builtin.unarchive:
        copy: false
        src: "{{ yubico_authenticator_download_path }}"
        dest: "/tmp"
        creates: "yubico-authenticator"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Move the extracted folder to /usr/local/bin
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: "/tmp/yubico-authenticator-6.4.0-linux/"
        dest: "{{ yubico_authenticator_target_path }}"
        mode: 0755
        owner: root
        group: root

    - name: Cleanup
      ansible.builtin.file:
        path: "{{ yubico_authenticator_download_path }}"
        state: absent
